$(window).scroll(function(){
			if($(window).scrollTop()>76){
				//锁定当前产品的导航条
				$("div.nav_local_product").css({"position":"fixed","width":"100%","top":0,"background-image":"url(nav_prd_bg.png)","background-repeat":"repeat-x"});
				$("#container").css("margin-top",50);
			}else{
				$("div.nav_local_product").css({"position":"static","width":"100%","background-image":""});
				$("#container").css("margin-top",0);
			}
			//检测是否有弹出窗口，有就收回去
		});